import { TEMP_CHAT } from 'helpers/constants/chat'
import { Chat } from 'store/posts/types'
import { generateEntityTempId } from './commons'

export function categorizeDate(arg: number): string {
  // Response comes in seconds or initially set ones are generated by Date.now. Eventually, to process date properly we convert it to milliseconds
  const inputDate = new Date(arg * 1000)
  const now = new Date()

  const inputYear = inputDate.getFullYear()
  const currentYear = now.getFullYear()

  if (inputYear < currentYear) return inputYear.toString()

  const inputMonth = inputDate.getMonth()
  const currentMonth = now.getMonth()

  const dayDifference = Math.floor((now.getTime() - inputDate.getTime()) / (1000 * 60 * 60 * 24))

  if (dayDifference === 0) return 'Today'
  if (dayDifference === 1) return 'Yesterday'
  if (dayDifference <= 7) return 'Last 7 days'
  if (inputMonth === currentMonth) return 'This month'
  return inputDate.toLocaleString('default', { month: 'long' })
}

export const generateTempChat = (): Chat => {
  const nowMs = Date.now()
  return {
    ...TEMP_CHAT,
    id: generateEntityTempId('temp-chat'),
    updatedDate: nowMs / 1000, // TODO: for set true date for first chat
  }
}
